### ISSUE TITLE
Create default tenant id and root api key using kickstart not working 

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#54] opened 2021-05-12 23:36 UTC
I am attempting to create default tenant id `9a39129e-0789-4a88-a66f-73f058ea6d2b` and root api key using the kickstart functionality:

```
  kickstart:
    enabled: true
    data:
      kickstart.json: |
        {
          "variables": {
            "defaultTenantId": "9a39129e-0789-4a88-a66f-73f058ea6d2b"
          },
          "apiKeys": [{
            "key": "somesupersecretapikeyhere",
            "description": "Root API Key"
          }]
        }
```

However after the pods come up, and I log into the web ui the default tenant id is not `9a39129e-0789-4a88-a66f-73f058ea6d2b` and there are no api keys created.

**Comment by drpebcak** [comment] 2021-05-13 07:41
Have you also done this part? https://github.com/FusionAuth/charts/blob/master/chart/values.yaml#L96

**Comment by nodesocket** [comment] 2021-05-13 23:11
@drpebcak thanks for the reply. Looking in my logs when I `helm install` I do see:

```
...
  - You are using a deprecated configuration property name of [FUSIONAUTH_KICKSTART]. The new allowed names for that property are [fusionauth-app.kickstart.file]
...
2021-05-13 11:08:34.970 PM WARN  io.fusionauth.api.service.system.kickstart.DefaultKickstartService - One or more API keys have already been added. Cannot kickstart.
```

Not sure I understand the message one of more API keys have already been added.

**Comment by nodesocket** [comment] 2021-05-13 23:15
@drpebcak though it did appear to work. I see the default tenanit id created with `9a39129e-0789-4a88-a66f-73f058ea6d2b` and a root api token.

**Comment by robotdan** [comment] 2021-05-14 03:13
> Not sure I understand the message one of more API keys have already been added.

That just means that while the kickstart file was configured, kickstart was not run because an API key has already configured. Kickstart is intended on run during initial startup with a clean database. Once an API key exists, or any other indication that some configuration has been completed, you will see that message. This way we don't run kickstart on each startup.

**Comment by nodesocket** [comment] 2021-05-17 16:13
@robotdan it was caused because we run multiple replicas of `fusionauth` and I am guessing they all try to invoke the `kickstart.json` thus the api key already exists error right?

**Comment by robotdan** [comment] 2021-05-17 16:59
In theory kickstart should be multi-node safe. During startup, one node gets promoted to master and will run kickstart if configured. All other nodes should sit and wait for this to complete. If more than one node attempts to run kickstart that would be a bug.

**Comment by drpebcak** [comment] 2021-05-17 21:03
It sounds like this is working as intended from the chart perspective, so I'm going to close this one.

**Closed by drpebcak** 2021-05-17 21:03 UTC
Labels: question
